name: flet_shimmer
description: Flet Shimmer control
repository: https://github.com/ositoMalvado/flet-shimmer/src/flutter/flet_shimmer
version: 0.1.0
homepage: https://github.com/ositoMalvado/flet-shimmer

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: ^0.27.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
